add "set -e" so scripts exit when child scripts exit with non-zero status

diff --git a/scripts/aws/upsert_cluster b/scripts/aws/upsert_cluster
--- a/scripts/aws/upsert_cluster
+++ b/scripts/aws/upsert_cluster
@@ -2,6 +2,8 @@
 
 # --- Upsert Kubernetes cluster on AWS --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -23,7 +25,7 @@ group_name="kops"
 # Ensure AWS environment variables are currently set.
 if [ ! "$AWS_ACCESS_KEY_ID" ] || [ ! "$AWS_SECRET_ACCESS_KEY" ]; then
 	echo "AWS environment variables not currently set.\nSet \"AWS_ACCESS_KEY_ID\" and \"AWS_SECRET_ACCESS_KEY\" and then try again."
-	exit
+	exit 1
 fi
 
 # Upsert AWS group.
diff --git a/scripts/aws/upsert_cname_record b/scripts/aws/upsert_cname_record
--- a/scripts/aws/upsert_cname_record
+++ b/scripts/aws/upsert_cname_record
@@ -2,6 +2,8 @@
 
 # --- Upsert CNAME record on Route53 --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 hosted_zone_id="$1"
@@ -12,17 +14,17 @@ record_val="$3"
 
 if [[ ! "$hosted_zone_id" ]]; then
 	echo "\"hosted_zone_id\" arg required. Exiting."
-	exit
+	exit 1
 fi
 
 if [[ ! "$record_name" ]]; then
 	echo "\"record_name\" arg required. Exiting."
-	exit
+	exit 1
 fi
 
 if [[ ! "$record_val" ]]; then
 	echo "\"record_val\" arg required. Exiting."
-	exit
+	exit 1
 fi
 
 # ======== UPSERT CNAME RECORD ======== #
diff --git a/scripts/create_cluster b/scripts/create_cluster
--- a/scripts/create_cluster
+++ b/scripts/create_cluster
@@ -2,6 +2,8 @@
 
 # --- Ingest args and prep them for provider-specific cluster-creation script --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -43,7 +45,7 @@ $this_dir/assert_env "${uppercase_role}_CLUSTER_NAME" "$cluster_name"
 # Ensure cluster name is available.
 if kubectl config get-clusters | grep "^${cluster_name}$" &>/dev/null; then
 	echo "Cluster \"$cluster_name\" already exists. Exiting."
-	exit
+	exit 1
 fi
 
 if [[ "$env" != "local" ]]; then
diff --git a/scripts/create_kubeconfig b/scripts/create_kubeconfig
--- a/scripts/create_kubeconfig
+++ b/scripts/create_kubeconfig
@@ -2,6 +2,8 @@
 
 # --- Create a fresh kubeconfig file for the specified environment --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -18,7 +20,7 @@ $this_dir/validate_arg "env" "$env" "local|dev|staging|prod"
 if [[ "$env" == "local" ]]; then
 	if [[ ! "$KUBECONFIG" ]]; then
 		echo "KUBECONFIG env var not currently set. Unsure which file to copy over into build image. Exiting."
-		exit
+		exit 1
 	fi
 
 	echo "Using local kubeconfig at \"$KUBECONFIG\"."
diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -2,6 +2,8 @@
 
 # --- Deploy Supported Application to Core Kubernetes Cluster of Specified Env Tier --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -41,12 +43,12 @@ image_version="$( docker images $image_repo | sed -n 2p | awk '{print $2}' )"
 
 if [[ ! "$image_version" ]]; then
 	echo "Couldn't find tag for Docker repository \"$image_repo\"...Exiting."
-	exit
+	exit 1
 fi
 
 if [[ "$image_version" == "<none>" ]]; then
 	echo "Tag for latest Docker repository \"$image_repo\" can't be \"<none>\"...Exiting."
-	exit
+	exit 1
 fi
 
 # Push Docker image to external repository.
@@ -59,7 +61,7 @@ kubectl config use-context "$cluster_name" 1>/dev/null
 
 if ! kubectl get nodes &>/dev/null; then
 	echo "Error fetching cluster nodes. Not deploying."
-	exit
+	exit 1
 fi
 
 # ======== DETERMINE DEPLOYMENT EXISTENCE ======== #
diff --git a/scripts/expose_local_deployment b/scripts/expose_local_deployment
--- a/scripts/expose_local_deployment
+++ b/scripts/expose_local_deployment
@@ -2,6 +2,8 @@
 
 # --- Expose local K8S deployment to a hostname locally -- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 # Parse args
@@ -30,7 +32,7 @@ $this_dir/assert_env "CORE_CLUSTER_NAME" "$cluster_name"
 # Ensure service doesn't already exist.
 if [[ $( kubectl get services | awk "{print $1}" | grep "^${deployment}$" ) ]]; then
 	echo "Service \"$deployment\" already exists...not creating."
-	exit
+	exit 1
 fi
 
 # Create new NodePort service for this deployment (we only use this type locally).
@@ -42,7 +44,7 @@ kubectl expose "deployment/$deployment" --type=NodePort
 # Ensure ingress doesn't already exist.
 if [[ $( kubectl get ing | awk "{print $1}" | grep "^${deployment}$" ) ]]; then
 	echo "Ingress \"$deployment\" already exists...not creating."
-	exit
+	exit 1
 fi
 
 echo "Creating ingress for service \"$deployment\"..."
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -2,6 +2,8 @@
 
 # --- Install everything required to get up and running with Sweet Tea --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # Directory of this script.
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
@@ -15,7 +17,7 @@ if [[ "$os" = "mac" ]]; then
 elif [[ "$os" = "unknown" ]]; then
 	# Exit early if not on mac or linux.
 	echo "Only Linux and Mac operating systems supported. Exiting..."
-	exit
+	exit 1
 fi
 
 # Install jq to help with bash json parsing.
@@ -46,6 +48,8 @@ $this_dir/install_redis
 $this_dir/$os/install_pg
 
 # Upsert local databases for dev and testing.
-$this_dir/setup_dbs
+# Commenting out for now and using cloud-based DBs even for local development.
+# ^This avoids the headache of exposing local dbs to a local minikube cluster.
+# $this_dir/setup_dbs
 
 echo "Done!"
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -2,6 +2,8 @@
 
 # --- Run supported application as either a Go binary or Docker image (and potentially as a daemon if Docker image) --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -31,12 +33,12 @@ if [[ "$run_type" = "image" ]]; then
 
 	if [[ ! "$image_version" ]]; then
 		echo "Couldn't find tag for Docker repository \"$image_repo\"...Exiting."
-		exit
+		exit 1
 	fi
 
 	if [[ "$image_version" == "<none>" ]]; then
 		echo "Tag for latest Docker repository \"$image_repo\" can't be \"<none>\"...Exiting."
-		exit
+		exit 1
 	fi
 
 	# Build the 'docker run' command.
diff --git a/scripts/upsert_local_cluster b/scripts/upsert_local_cluster
--- a/scripts/upsert_local_cluster
+++ b/scripts/upsert_local_cluster
@@ -2,6 +2,8 @@
 
 # --- Upsert local K8S cluster with minikube --- #
 
+set -e # exit if any child script exits with non-zero status
+
 # ======== PARSE ARGS ======== #
 
 this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -18,7 +20,7 @@ $this_dir/validate_arg "cluster_name" "$cluster_name"
 # Ensure minikube is installed.
 if [[ ! "$( which minikube )" ]]; then
 	echo "Minikube not detected...run 'make install' and then try again."
-	exit
+	exit 1
 fi
 
 # ======== GET USABLE K8S VERSION ======== #
