add deploy logic split at NEW_DEPLOY

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -41,17 +41,38 @@ if [[ ! "$DEPLOY_ENV_VAL_SUPPORTED" ]]; then
 	exit
 fi
 
-# ======== VALIDATE CLUSTER ======== #
+# ======== SPECIFY/VALIDATE CLUSTER ======== #
 
+# Get cluster name from envs.
 cluster_name=$( $THIS_DIR/env_reader "$APP" "$DEPLOY_ENV" "CLUSTER_NAME" )
 
-# Get image name from script
-IMAGE_NAME=$( $THIS_DIR/docker_images "$APP" )
+# Switch to cluster context.
+kubectl config use "$cluster_name"
 
-# Get app-agnostic env vars from proper file
-docker_image_owner=$( $THIS_DIR/env_reader "$APP" "$DEPLOY_ENV" "DOCKER_IMAGE_OWNER" )
+if ! kubectl get nodes; then
+	echo "Error fetching cluster nodes. Not deploying."
+	exit
+fi
 
-# TODO: Group logic by kubectl run vs. kubectl update
+# ======== DETERMINE DEPLOYMENT EXISTENCE ======== #
+
+image_name=$( $THIS_DIR/docker_images "$APP" )
+image_owner=$( $THIS_DIR/env_reader "$APP" "$DEPLOY_ENV" "IMAGE_OWNER" )
+image_repo="$image_owner/$image_name"
+resource_name="$image_name"	# unique suffix will be added for job deploys
+
+# Always make a new deploy for deploys that are actually 'jobs'
+if [[ "$APP" = "migrate" ]]; then
+	NEW_DEPLOY="true"
+
+	# For a job, the resource name needs to differ with each deploy, so generate a uid for suffix.
+	job_uid="TODO"
+	image_name="$image_name-$job_uid"
+else
+	# For 'deployments', check to see if they already exist first.
+	# This will determine whether we should 'kubectl run' or simply 'kubectl update'.
+	echo "TODO"
+fi
 
 # ======== FORMAT DEPLOY ARGS ======== #
 
@@ -62,4 +83,9 @@ deploy_envs=$( $THIS_DIR/env_reader "$APP" "$DEPLOY_ENV" "all" "true" )
 
 # ======== DEPLOY ======== #
 
-kubectl run "$IMAGE_NAME" --image="$docker_image_owner/$IMAGE_NAME" $port $replicas $restart $deploy_envs
+if [[ "$NEW_DEPLOY" ]]; then
+	kubectl run "$resource_name" "--image=$image_repo" "$port" "$replicas" "$restart" "$deploy_envs"
+else
+	container_name="$image_name"
+	kubectl set image "deployment/$resource_name" "$container_name=$image_repo:latest"
+fi
